tasks:
  command-0:
    name: "Task 0: UV Setup"
    command: |
      pip install uv
      PIP_USER=false uv sync
    triggeredBy:
      - postDevcontainerStart
  command-1:
    name: "Task 1: Pre-commit Setup"
    command: |
      pip install pre-commit
      pre-commit install
      PIP_USER=false pre-commit install-hooks
      PIP_USER=false pre-commit install --install-hooks -t commit-msg
    triggeredBy:
      - postDevcontainerStart
