tasks:
  command-0:
    command: |
      pip install uv
      PIP_USER=false uv sync
    description: init task migrated from .gitpod.yml
    name: "Task 0: command"
    triggeredBy:
      - postDevcontainerStart
  command-1:
    command: |
      pip install pre-commit
      pre-commit install
      PIP_USER=false pre-commit install-hooks
    description: init task migrated from .gitpod.yml
    name: "Task 1: command"
    triggeredBy:
      - postDevcontainerStart
